# Site settings
title: grimdocs
email: info@grimdocs.com
description: Technical documentation and communications
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
